- name: Retrieve vault secrets
  hosts: localhost
  connection: local
  tasks:
    - name: Get secret KV
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=demo/ssh:username token={{ token }} url=http://vault.srikanth553.store:8200') }}"